### ISSUE TITLE
TwitchClient fails to reconnect fully

### ISSUE THREAD

**Issue by MattEqualsCoder** [TheTrackerCouncil/SMZ3Randomizer#167]
So when there are issues with Twitch chat, Tracker will disconnect and mention that you need to save and restart tracker, and this is a work around, it's still not ideal. Unfortunately the library we currently use reconnects to Twitch but doesn't seem to actually rejoin chat properly.

My thoughts of resolving this are to either do one of the following

1. See if we can forcefully rejoin chat
2. See if we can recreate the TwitchClient object on disconnect
3. See if we can find a replacement Twitch chat library

**Comment by Vivelin** [comment]
I think I had rejoining channels at first, but that would cause everything to be duplicated. If we can't figure this out easily, I suggest we replace this library entirely. If there isn't a better one available, I could probably make a better one.
