### ISSUE TITLE
Better credits

### ISSUE THREAD

**Issue by Vivelin** [TheTrackerCouncil/SMZ3Randomizer#174]
The credits section of the README is getting a little out of hand. 

Maybe I could do something like https://alttpr.com/en/sprite_preview - sprite previews with name and credits per sprite, with separate sections for Samus, Link and Samus’ ship.

**Comment by MattEqualsCoder** [comment]
So the built in rando shows all of the people who created the sprites, so I assume we just want something to display here on GitHub before downloading. I wonder if we could have a script that will generate a new sprite credits markdown or something. 🤔 I think _technically_ a github action could even run on merge requests and create a new commit.

**Comment by MattEqualsCoder** [comment]
So we actually have the GitHub pages with the sprite credits now. Anything else need to happen with this, or should we close?

**Comment by Vivelin** [comment]
I think this is good for now.
