### ISSUE TITLE
Need to upgrade dotnet install github action

### ISSUE THREAD

**Issue by MattEqualsCoder** [TheTrackerCouncil/SMZ3Randomizer#456]
We're getting the following warning when github actions run:

```
The following actions uses node12 which is deprecated and will be forced to run on node16: actions/setup-dotnet@v1. For more info: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
```

The problem is, upgrading to the latest version runs .net 8, which makes a bit of changes. It adds the commit to the build version, which then gets appended to the download and in the UI. 

![image](https://github.com/Vivelin/SMZ3Randomizer/assets/63823784/d494d2c8-3424-40b1-b17e-b2e13670aa28)

It also greatly increases build sizes. Here's a previous version in comparison:

![image](https://github.com/Vivelin/SMZ3Randomizer/assets/63823784/065bb141-25e6-4ebc-b7d7-fb58af042403)

Upgrading also throws this warning:

```
For projects targeting .NET 8.0 and higher, specifying a RuntimeIdentifier will no longer produce a self contained app by default. To continue building self-contained apps, set the SelfContained property to true or use the --self-contained argument.
```

I guess first question is if we want the git commit to be included in the build number. If we want to disable it fully, we can include the following in the project:

```
<IncludeSourceRevisionInInformationalVersion>false</IncludeSourceRevisionInInformationalVersion>
```

Otherwise, we may want to try to clean up the download/installer file names perhaps. And the about screen is kind of messed up with it as well.

For the filesize, .net 8 changed to self contained being default. To revert to the way it was before, we need to add --self-contained false to the publish.

**Comment by Vivelin** [comment]
I don't mind Git commit hashes to be part of the assembly version, but it doesn't really make sense to put that anywhere else, in my opinion.
