### ISSUE TITLE
"Speech recognition mode" set to "Disabled" crashes app when clicking Launch

### ISSUE THREAD

**Issue by poolfloat** [TheTrackerCouncil/SMZ3Randomizer#477]
Wanting to disable voice input for the built-in tracker, changing "Speech recognition mode" from the PTT default to Disabled causes the app to crash when clicking Launch.

![image](https://github.com/TheTrackerCouncil/SMZ3Randomizer/assets/24301755/7a1106a6-b7ab-40b3-aee2-1dd5378665be)

Changing this setting to anything else appears to cause a crash. I was able to set "Tracker voice frequency" to Disabled without issue.

[smz3-cas-20240325.log](https://github.com/TheTrackerCouncil/SMZ3Randomizer/files/14737968/smz3-cas-20240325.log)

**Comment by MattEqualsCoder** [comment]
I think I see what the issue is looking at the logs. I think for now, you can probably lower the tracker recognition and confidence thresholds to 0 to disable tracker.

**Comment by MattEqualsCoder** [comment]
@poolfloat FYI, just in case we don't push out a new version this week, you can download the in flight version with this fix here: https://github.com/TheTrackerCouncil/SMZ3Randomizer/actions/runs/8422671214
