### ISSUE TITLE
Setting Shaktool to Progressive Item Always Results in Progressive Shield

### ISSUE THREAD

**Issue by doomcup** [TheTrackerCouncil/SMZ3Randomizer#486]
For some reason, setting InnerMaridiaSpringBall to Progression Items always places a progressive shield there. When testing it via Generate Stats, it's placed there 1000 out of 1000 times.

This is in the latest Windows version, 9.7.4

**Comment by Vivelin** [comment]
I just ran a quick test myself. Cas' Logic options don't affect this, turning all of them off (or on) gives the same result.

@MattEqualsCoder do you have any idea what could be happening?

**Comment by MattEqualsCoder** [comment]
Not off the top of my head, no. I knew it struggled to have really good progression items in hard to get to locations, but I would have expected things like the mushroom, ice bream, etc. to be there at least. I wonder if other locations have this same issue
