### ISSUE TITLE
Autotracker lua Fails under newest version

### ISSUE THREAD

**Issue by doomcup** [TheTrackerCouncil/SMZ3Randomizer#506]
Updated to the latest RC version under Windows 64-bit, but when attempting to connect the autotracker, SNES9x-rr responds with "Failed to open socket:connection refused" and *severe* lurching. Nothing has changed with my setup except installing 9.8.0-rc.2

**Comment by doomcup** [comment]
I tried an uninstall and a reinstall, and the reinstall didn't actually put any lua scripts anywhere. It's possible this is something on my end, because for some reason the installer wouldn't run unless I ran it from the terminal.

**Comment by CPColin** [comment]
The RC does indeed install the scripts in a different folder. I think maybe they moved up a directory?

**Comment by MattEqualsCoder** [comment]
Ah, yeah. Apologies, I didn't add any notes about that in the release notes. I'll make sure to do that.

The default AutoTracking scripts folder is %localappdata%\SMZ3CasRandomizer\AutoTrackerScripts, and you'll want to use the connector.lua file.

**Comment by doomcup** [comment]
I solved my installer problem. Windows Defender SmartScreen *hates* the installer, and I had to disable it to get the installer to run normally. 

As you said, generating a new seed put the tracker scripts where they should be. thanks.

**Comment by MattEqualsCoder** [comment]
Is there anything else that comes up in the the snes9x lua log?

**Comment by doomcup** [comment]
![image](https://github.com/TheTrackerCouncil/SMZ3Randomizer/assets/47144764/dca3edc9-0108-4ebc-a145-b7952f0db48f)
This, on a loop.

**Comment by MattEqualsCoder** [comment]
Bizarre, I can't seem to replicate this in either 32bit or 64bit snes9x. Can you post the full log from snes9x as well as the latest log file from %localappdata%\SMZ3CasRandomizer? I'll try with my laptop to see if I can replicate in the meantime.

**Comment by MattEqualsCoder** [comment]
Also, just to make sure, you're using just the regular "Lua Script" connector option in SMZ3 and not the EmoTracker Lua Script or Crowd Control Lua Script?

**Comment by doomcup** [comment]
I found out what was going on. Before the update I had it do LUA scripting by default. Something got messed up and it decided to do USB2SNES by default, and would not be switched from it.

I went into the randomizer config dialog and switched it to LUA and it's working now.

**Comment by MattEqualsCoder** [comment]
It looks like part of what may have happened is when you were troubleshooting the script initially, you may have switched the tracker window over to USB2SNES, and that sort of stuck. You then got the latest scripts, but it was still set to USB2SNES.

However, you should have been able to switch on the tracker window. Not sure why that wasn't working, and I'm unable to replicate. I'll do some more testing. Glad you got it working, and I'll make an update in the release notes telling people they may need to change the option in the dropdown. Sorry you had problems from this.

**Comment by MattEqualsCoder** [comment]
I did document this in the release, and I haven't heard of any other issues. Closing this unless we hear about anything new.
