### ISSUE TITLE
Tracker Doesn't Count Progressive Sword as Essential or Nice to Have

### ISSUE THREAD

**Issue by doomcup** [TheTrackerCouncil/SMZ3Randomizer#516]
I can't find whether this is intentional or not. Was going through the attached seed and I asked tracker what was in Palace of Darkness. I was told I could skip it, so I had tracker clear the dungeon.

After spending a few hours trying to find the last couple sword upgrades, I get told that I've cleared every area with a sword, despite only having level 3. I resort to reading the spoiler log and find it was in Palace of darkness.

Seed: 2014318415

Randomizer settings string:

[randomizer_settings_string.txt](https://github.com/TheTrackerCouncil/SMZ3Randomizer/files/15484711/randomizer_settings_string.txt)

**Comment by MattEqualsCoder** [comment]
Been trying this out, and I can't replicate it, even with the settings string and seed you posted. Are you sure she didn't say something like "It can be skipped, but you might like what's there?"

**Comment by doomcup** [comment]
It's possible it could have been phrased that way but I missed it. Since you can't replicate it, it must be the case. Thanks for checking though

**Comment by MattEqualsCoder** [comment]
I think we can go ahead and close this out. Please let us know if you run into this again.
