### ISSUE TITLE
Broken Tracker Logic: Bow requires Varia Suit, Varia Suit Requires Bow

### ISSUE THREAD

**Issue by doomcup** [TheTrackerCouncil/SMZ3Randomizer#517]
Checking the spoiler log, it seems to think I can get past the Armos Knights without a bow.

Seed: 1805285215

Settings: 
[settings_string.txt](https://github.com/TheTrackerCouncil/SMZ3Randomizer/files/15492395/settings_string.txt)

**Comment by CPColin** [comment]
Do you mean the icy Armos Knights in GT? Between the sword, the hammer, and the ice rod, you should be able to take them down. It'll take a bit, though!

**Comment by doomcup** [comment]
Huh, I legitimately didn't think they were vulnerable to anything else. Thanks

**Comment by CPColin** [comment]
No prob!
