### ISSUE TITLE
Mutiworld not working

### ISSUE THREAD

**Issue by BrysonK18** [TheTrackerCouncil/SMZ3Randomizer#526]
When Me and my brother try to connect the multiword services it won't let us connect. Do you know what the problem is and how do I fix it?

**Comment by MattEqualsCoder** [comment]
Whoops, sorry about that! I transitioned hosts, and apparently I flubbed up a config. Can you give it another go when you have a chance?

**Comment by MattEqualsCoder** [comment]
Looking at the logs, it seems like someone played a full game on the 18th. Considering this closed unless we hear back about other issues.
