### ISSUE TITLE
Reset defaults/update Emulator launcher

### ISSUE THREAD

**Issue by clion520** [TheTrackerCouncil/SMZ3Randomizer#540]
I got the current SNES9x Emulator and then saw the LUA Autotrack script was tied to a 1.60 version. added in the older version, removed the newer one but now I crash everytime I try to start and can not figure out a reset to defaults/update emulator option.

**Comment by MattEqualsCoder** [comment]
By default, it uses the default application for roms that is set by your OS. You'll need to look up how to do that for your specific OS as I think it is slightly different between each version of Windows. 

Alternatively, if you get the path to the specific version of snes9x-rr you have, you can set the exe as the launch application path in the randomizer settings.

**Comment by clion520** [comment]
Yeah I renamed the folder to the existing path as the exe was the same name.  Also yes updating my default program for windows worked as well.  Thank you.
