### ISSUE TITLE
Add Resize Tracker Window Button

### ISSUE THREAD

**Issue by MattEqualsCoder** [TheTrackerCouncil/SMZ3Randomizer#549]

**Comment by Vivelin** [comment]
What do you mean by this? A button to auto-resize the window to fit the content?

**Comment by MattEqualsCoder** [comment]
Yeah. I brought up the possibility of genuinely automatically resizing the window, but Pink had concerns about that as a streamer. So, my idea was to add a button that would for a one-time update the tracker window to the necessary size to fit all of the current columns and windows.
