### ISSUE TITLE
Archipelago Mode

### ISSUE THREAD

**Issue by MattEqualsCoder** [TheTrackerCouncil/SMZ3Randomizer#577]
Inspired by Pink, it would be nice if we could introduce a mode for using tracker with Archipelago.

- Select rom (and possibly spoiler file?)
- Allow users to add various Cas' patches
- Use as close as we can to the mainline SMZ3 logic for map purposes
- Read memory of the gifted items to update items gifted from other players

**Comment by CPColin** [comment]
I wonder if we can add some extra idle lines for this mode, like, "Can't find anything in the other games either, huh?"

**Comment by Vivelin** [comment]
I know it's massively out of scope for this, but if at least some of the work into this issue could benefit a more generic application of Tracker for other games would be cool. Obviously, it can't receive the same attention to detail as we do with SMZ3, but with layouts and lines being customizable, I don't think we're _too_ far off from being able to support other games with limited functionality.

**Comment by MattEqualsCoder** [comment]
I definitely would love to make tracker work with more games, but I think it might not be super trivial really.

I think from the most fundamental perspective, the main issue is the logic. Most people would probably want us to have some sort of location or map tracker, otherwise they would need two trackers. So we'd have to integrate the logic from other trackers into our system somehow. And when we do that, it starts getting messy fast I feel unless we were to be super careful.

After that, I think just the biggest problem is we probably have a lot of code around that really assumes it's SMZ3. Tracker.cs has a ton of SMZ3 specific conditions and things, for example.

I have mused about it a bit, though. I think if we were to pull out the game specific stuff into separate projects, we could keep the game specific stuff isolated.

Might be something to consider though. Maybe not in a we do something with one release. But maybe slowly move SMZ3 specific things slowly into a separate project within the solution.

**Comment by Vivelin** [comment]
Yeah, that's fair. Just asking if it's worth keeping that in mind while we do Archipelago-specific stuff. Do what we can while we're making the changes for this.
