### ISSUE TITLE
Make the combined map for both light and dark world the default for auto tracker map updates

### ISSUE THREAD

**Issue by kyranz** [TheTrackerCouncil/SMZ3Randomizer#581]
While using the auto tracker option to automatically switch to the current played map, make the default for Alttp the combined map for light and dark world, or add an option to toggles this.

Would make it easier to visualize items that require use of the magic mirror.

**Comment by MattEqualsCoder** [comment]
I can probably have an option for either "by region" or "by game".

**Comment by kyranz** [comment]
Would it be possible to have this option be individual per game? Because in Alttp i like having both worlds at the same time, while in Super Metroid, i think having only the current region is better.

**Comment by MattEqualsCoder** [comment]
@kyranz This has now been released in the newest version, as an FYI
