### ISSUE TITLE
Clicking "Don't Check for Updates" on the main window does not properly disable updates

### ISSUE THREAD

**Issue by SebDaMuffin** [TheTrackerCouncil/SMZ3Randomizer#582]
The `DisableUpdate()` method sets `_options.GeneralOptions.CheckForUpdatesOnStartup` to `true` instead of `false`.

https://github.com/TheTrackerCouncil/SMZ3Randomizer/blob/b69a0cb9fbbb6a874fb2e611ad0f48ac35c01a27/src/TrackerCouncil.Smz3.UI/Services/MainWindowService.cs#L44-L49

**Comment by MattEqualsCoder** [comment]
Whoops. Thankfully, it appears the option in the settings does work, so until a new version is made, you should be able to use that.
