### ISSUE TITLE
Push To Talk not working

### ISSUE THREAD

**Issue by LiminalityCarb** [TheTrackerCouncil/SMZ3Randomizer#587]
I'm not sure if I'm missing something, but it seems the tracker's Push-To-Talk option isn't working.  I've tried toggling it on, and tried it with "Left control", "F13" (my current Discord PTT), and "F14" (my split button in live split) and tracker never hears what I say.  It just says "Voice Disabled" on the tracking screen.  Is there some nuance I'm missing or is PTT not working currently?

**Comment by MattEqualsCoder** [comment]
I'll try to take a look. I'm not aware of any issues, but I'm not sure how many people use the feature.

**Comment by MattEqualsCoder** [comment]
Sorry about this. Seems like it was broken with the cross platform change. Fix should be up in the next day.
