### ISSUE TITLE
Guided Initial Setup

### ISSUE THREAD

**Issue by MattEqualsCoder** [TheTrackerCouncil/SMZ3Randomizer#609]
This spawned from a discussion in Pink's server about why the sassy profile is the default. I don't think we'd want to make the sassy profiles not be the default, so maybe we can have some sort of simplified guided setup when first opening? 

We could have it contain the most common settings (ROM directories, for example), and part of this setup could have something to help people pick the right set of profiles for them.

**Comment by MattEqualsCoder** [comment]
So my idea here would be to have some sort of wizard like interface with prev/next buttons when you first start the application the first time that has a page-by-page setup with the most important settings and a bit more description around what the application is capable of doing and what each setting means.

Page 1: Directories
- ALttP Rom
- SM Rom
- Output Folder
- MSU Folder (include button to check on how many MSUs are detected)

Page 2: Basic Tracking Options
- Default auto tracker connection
- Auto tracker connection settings
- Auto tracker map update 
- Auto track viewed events
- Enable timer

Page 3: Tracker Options
- Disable/Enable voice recognition and TTS (I'm surprised we don't already have this option)
- Tracker image pack
- Tracker profiles (list our built in configs with descriptions)
  - We would handle the order ourselves to simplify things (BCU Icons first -> Sassy -> other order doesn't matter)

Page 4: MSU Display Options
- Option to open the MSU display by default
- Song display style (with preview)
- Song output file path
- Enable MSU Randomizer message server

Page 5: Twitch Integration
- Login
- Chat functionality
- GT guessing game style

Page 6: Misc Settings
- Launch options
- Update options

**Comment by Vivelin** [comment]
That... sounds way too complicated, honestly. A wizard with 6 pages?

I think it's a good idea for the settings that _need_ to be set up, like the base ROMs and what kind of emulator/autotracker you use.

But I think for a lot of things, having sane defaults makes more sense; and where that's not possible, make it easy to find. For example, if I generate a custom ROM, I immediately see the sprites that will be used, so I know that can be changed right there. The other tabs also show there's more to be configured if you want.

As for the profiles; I wonder if renaming the default to "Basic" and then renaming "Sassy" to something like "Default (Sassy)" or "Sassy (default)" would clear up that, at least. Maybe we should give profiles descriptions?

**Comment by CPColin** [comment]
I like that shorter option, especially the first page, because I remember fumbling around for a bit before I had the right ROM files selected.

**Comment by Vivelin** [comment]
I do think a wizard would be better for forcing users to go through certain settings, and simplifying others.

For profiles, we could narrow it down to a few Yes/No questions. 
1. "_Do you want Tracker to talk to you?_ Yes/No" 
2. "_Can Tracker say bad words?_ Hell yes / Heck no" 
3. "_Do you know Betus?_ \<some sort of in-joke answer for yes> / Who?"

I'd honestly keep Basic/Default and Sassy enabled at all times (but still let users turn it off later in settings if they really want a basic-only Tracker).

**Comment by MattEqualsCoder** [comment]
Well, neo's complaint *was* that sassy was enabled by default. And maybe the answer is just "sorry, that's just how it is. Dig into the settings to disable that." 

But to your yes/no questions, we could do maybe add something like "Do you want Tracker to have a personality? Yes, bring on the sass / No, give me boring business tracker"

**Comment by CPColin** [comment]
"What do you know about the_betus's missing butcher knife?" "#content" "(GRAHAM SCREAM)"
