### ISSUE TITLE
Crash while generating seed in linux version

### ISSUE THREAD

**Issue by doomcup** [TheTrackerCouncil/SMZ3Randomizer#613]
Finally got some time to test the linux port, hit generate, and the error message thingy popped up. Doing this under devuan daedalus on amd64, appending log

[smz3-cas-20241207.log](https://github.com/user-attachments/files/18050475/smz3-cas-20241207.log)

**Comment by MattEqualsCoder** [comment]
I'll take a look when I can tomorrow  Not too familiar with that distro, but if you got the error popup it must be somewhat trying to work.

**Comment by MattEqualsCoder** [comment]
@doomcup Have you tried possibly re-opening it and seeing if it works now? It looks like there may be some timing issues, and it tried to load all of the tracker profiles before they were put in the proper location. I'll have to look into why that may be the case. But, it looks like it did move it to the correct location after, so I think they may be where they need to be for you now.

**Comment by doomcup** [comment]
Looks like you're right. I've tested it since and it's done a couple more seeds without issue.

Also Devuan's just a fork of Debian without systemd, by a bunch of former Debian devs.
